name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["8.2", "8.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: sqlite3, mbstring, dom, fileinfo
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Prepare environment
        run: |
          cp .env.example .env || true
          php artisan key:generate --ansi || true

      - name: Static Analysis (PHPStan / Larastan)
        run: composer run stan

      - name: Lint (Pint)
        run: ./vendor/bin/pint --test

      - name: Run Tests (Pest)
        run: composer run test

      - name: Combined Verify Script
        if: always()
        run: composer run verify

